estandar/urls.py
from django.contrib import admin
from django.urls import path, include

from django.contrib.auth import views as auth_views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("registro.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
]

from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from estandar import settings

urlpatterns += staticfiles_urlpatterns()

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#print(urlpatterns)

registro/urls.py
from django.urls import path
from . import views

app_name = 'registro'

urlpatterns = [
        path('', views.inicio, name='inicio'),
        path('ayuda', views.instrucciones, name='instrucciones'),
        path('nuevo/codigo', views.nuevo_codigo, name='nuevo-codigo'),
        path('nuevo/codigo/comentarios', views.nuevo_codigo_comentarios,
             name='nuevo-codigo-comentarios'),
        path('nuevo/plano', views.nuevo_plano, name='nuevo-plano'),
        path('codigos', views.EstandarLista.as_view(),
             name='codigos-listview'),
        path('codigos/<slug>', views.EstandarDetalle.as_view(),
             name='codigos-detailview'),
        path('codigos-porcategoria', views.listacodigosporcategoria,
             name='codigosporcategoria'),
        path('planos', views.plano_lista, name='listaplanos'),
        path('planos/<int:ot>', views.plano_detalle, name='detalleplano'),
        path('catalogo', views.catalogo, name='catalogo'),
        ]

registro/forms.py
import base64
from django import forms
from django.forms import ModelForm, Form, widgets
from django.forms.formsets import formset_factory
from django.utils.safestring import mark_safe
from django.utils.text import slugify
from django.core.files.base import ContentFile
from .models import *


class PastedImageWidget(widgets.Widget):
    def render(self, name, value, attrs=None, renderer=None):
        if value is None:  # though it's always None so far
            html = "<img id='id_imagen' alt='(ctrl+v p/ pegar)'/>"
        else:
            html = "<img id='id_imagen' src='%s'/>" % value
        return mark_safe(html)


class RegistroForm(ModelForm):
    imagen_container = forms.CharField(required=False,
                                       widget=forms.HiddenInput())

    class Meta:
        model = Estandar
        exclude = ['autor']
        widgets = {'imagen': PastedImageWidget()}

    # need this to complain in case no 'imagen' is pasted
    def clean(self):
        # https://github.com/twoscoops/two-scoops-of-django-1.8/issues/64
        # (this is the right way to check fields, when auto-check is off)
        cleaned_data = super(RegistroForm, self).clean()
        imagen_container = cleaned_data.get("imagen_container")
        if imagen_container == "":
            self.add_error('imagen_container', 'Agregar imagen!')

    def save(self, commit=True):
        self.instance.imagen.delete(False)
        self.instance.codigo = self.instance.codigo.lower()  # force lowercase
        imgdata = self.cleaned_data['imagen_container'].split(',')
        try:
            ftype = imgdata[0].split(';')[0].split('/')[1]
            fname = slugify(self.instance.codigo)
            self.instance.imagen.save(
                    '%s.%s' % (fname, ftype),
                    ContentFile(
                        base64.decodebytes(bytes(imgdata[1], 'utf-8'))))
        except:
            raise
            print('could not save file!')
        return super(RegistroForm, self).save(commit=commit)


class ComentariosForm(ModelForm):
    class Meta:
        model = Comentarios
        exclude = ['codigo', 'autor']

    def save(self, codigo, commit=True):
        self.instance.codigo = Estandar.objects.get(codigo=codigo)
        self.instance.save()
        return super(ComentariosForm, self).save(commit=commit)


# used in self-made list-view to show codigos...
# to filter by category and-or (un)select show-images
class FilterCodigosForm(Form):
    mychoices = [('All', 'Mostrar Todos')]
    try:
        mychoices.extend(list(zip(Categoria.objects.all(),
                                  Categoria.objects.all())))
    except:
        pass
    filtro = forms.ChoiceField(widget=forms.Select(
                                             attrs={'onchange': 'submit()'}),
                               choices=mychoices)
    # https://tuts-station.com/django-form-checkbox-validation-example.html
    mostrarimagenes = forms.BooleanField(label='Mostar imagenes?',
                                         required=False,
                                         widget=forms.CheckboxInput(
                                             attrs={'onchange': 'submit()'}))


class PlanoForm(ModelForm):
    class Meta:
        model = Plano
        exclude = ['fecha', 'autor', 'ultima_generacion_imagen']


class DetallePlanoForm(ModelForm):
    class Meta:
        model = DetallePlano
        exclude = ['planoid', 'autor']
        # https://docs.djangoproject.com/en/1.10/topics/forms/modelforms/#overriding-the-default-fields
        labels = {'codigo': 'Código',
                  'tipo': 'Vidrio',
                  'ancho_mm': 'Ancho [mm]',
                  'alto_mm': 'Alto [mm]',
                  'comentario': 'Comentario (opcional)'}
        widgets = {'cantidad': forms.NumberInput(attrs={"min": "1",
                                                        "max": "20",
                                                        "value": "1"}),
                   'ancho_mm': forms.NumberInput(attrs={"min": "100",
                                                        "max": "3000"}),
                   'alto_mm':  forms.NumberInput(attrs={"min": "100",
                                                        "max": "3000"}),
                   'tipo':     forms.Select(attrs={"class": "tipo-select"})}

registro/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.forms import formset_factory
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.contrib.auth.decorators import login_required
from datetime import datetime

# to fix the "received a naive datetime" warning
from django.utils import timezone
# -> https://stackoverflow.com/questions/18622007/runtimewarning-datetimefield
#    -received-a-naive-datetime#20106079

from . import models
from . import forms
from django.conf import settings
from .utils import generarplanos

from django.db.utils import IntegrityError


MAX_PANOS_POR_PLANO = 20


def buscador(request):
    # aca quiero poner algo asi como un buscador...
    # '''
    # que uno pueda buscar por codigo por ejemplo... lo cual se puede lograr
    # con un dropdown nomas
    # tambien podria filtrar por categoria, por ejemplo
    # incluso hacer un AND u OR (mostrar los que tengan alguna coincidencia con
    # el codigo y/o con la categoria elegida)
    # tambien puede ser buscar por comentarios (y mostrar ahi matches)
    # '''

    return render(request, template_name='registro/buscador.html')


@login_required
def nuevo_codigo(request):
    if request.method == "POST":
        form = forms.RegistroForm(request.POST, request.FILES)
        form.fields['imagen'].required = False
        if form.is_valid():
            form.instance.autor = request.user
            formtosave = form.save()
            codigo = formtosave.codigo
            formtosave.save()
            return HttpResponseRedirect(reverse("registro:codigos-detailview",
                                        args=[codigo]))
            #url = reverse("registro:nuevo-codigo-comentarios"
            #              )+"?codigo="+codigo
            #return redirect(url)
            # (not now)
    else:
        form = forms.RegistroForm()

    return render(request,
                  template_name="registro/nuevo-codigo.html",
                  context={'form': form})


@login_required
def nuevo_codigo_comentarios(request):
    ComentariosFormSet = formset_factory(forms.ComentariosForm)
    codigo = request.GET.get('codigo')
    if request.method == "POST":
        formset = ComentariosFormSet(request.POST)
        if formset.is_valid():
            for form in formset:
                form.instance.autor = request.user
                form.save(codigo=codigo)
            return HttpResponseRedirect(reverse("registro:codigos-detailview",
                                        args=[codigo]))
    else:
        formset = ComentariosFormSet()
        estandarobj = get_object_or_404(models.Estandar, codigo=codigo)

    return render(request,
                  template_name="registro/nuevo-codigo-comentarios.html",
                  context={'formset': formset,
                           'codigo': codigo})


# only one view is enough here, not good ui otherwise
@login_required
def nuevo_plano(request):
    # we use formsets since the final form will be a combination of
    # the plano form (one 'plano-id' (aka 'ot') numerical text input field)
    # and one or more 'plano-detalle' forms (details), the formsets
    DetallePlanoFormSet = formset_factory(forms.DetallePlanoForm,
                                          min_num=1, extra=0, max_num=6)
    error_message = None

    if request.method == "POST":
        # forms with post data
        ot_form = forms.PlanoForm(request.POST)
        plano_formset = DetallePlanoFormSet(request.POST)

        # both shoud be valid
        if ot_form.is_valid() and plano_formset.is_valid():
            try:
                ot_form.instance.autor = request.user
                ot_form.instance.fecha = datetime.now(tz=timezone.utc)
                ot_formtosave = ot_form.save()
                print("to_form_to_save = ", ot_formtosave)
                planoid = ot_formtosave.planoid

                forms_to_save = []
                for form in plano_formset:
                    form.instance.planoid = models.Plano.objects.get(
                            planoid=planoid)
                    # let's be careful here.. it could be saving the first
                    # formsets but not all
                    forms_to_save.append(form.save())
                cant_total_panos = sum([form.cantidad
                                        for form in forms_to_save])
                if (cant_total_panos > MAX_PANOS_POR_PLANO):
                    error_message = "Se permiten como máximo 20 paños por plano"
                else:
                    for form in forms_to_save:
                        form.save()
                    ot = ot_formtosave.ot
                    ot_formtosave.save()

                    return HttpResponseRedirect(
                            reverse("registro:detalleplano",
                                    args=[ot]))
            except IntegrityError:
                error_message = "No se puede repetir la combinación (código, vidrio, ancho, alto, comentario). Probá sumar las cantidades."

    else:
        ot_form = forms.PlanoForm()
        plano_formset = DetallePlanoFormSet()

    return render(request,
                  template_name="registro/nuevoplano.html",
                  context={'ot_form': ot_form,
                           'plano_formset': plano_formset,
                           'error_message': error_message})


# another view, little pics included
def codigos_alt(request):
    return render(request,
                  template_name="registro/codigos-alt.html",
                  context={'estandar': models.Estandar.objects.all()})


def listacodigosporcategoria(request):
    # dirty but works... refactor later (20221030)
    if request.method == "POST":
        filtro_value = request.POST.get('filtro')
        if (filtro_value == "All"):  # all categories
            categorias = models.Categoria.objects.all()
            codigos = dict(zip(categorias,
                               map(lambda x: x.estandar_set.all(),
                                   categorias)))
        else:  # one category
            categoria = models.Categoria.objects.get(categoria=filtro_value)
            codigos = dict([(categoria,
                           categoria.estandar_set.all())])
        codigosfilter = forms.FilterCodigosForm(request.POST)
        showimages = request.POST.get('mostrarimagenes')
    else:  # start
        categorias = models.Categoria.objects.all()
        codigosfilter = forms.FilterCodigosForm()

        codigos = dict(zip(categorias,
                           map(lambda x: x.estandar_set.all(),
                               categorias)))
        showimages = False  # hardcoded for now

    return render(request,
                  template_name="registro/listacodigos.html",
                  context={'codigos': codigos,
                           'selectfilter': codigosfilter,
                           'showimages': showimages,
                           'MEDIA_URL': settings.MEDIA_URL})


class EstandarLista(ListView):
    model = models.Estandar


class EstandarDetalle(DetailView):
    model = models.Estandar
    # https://stackoverflow.com/questions/68512060/slugfield-not-working-if-field-name-is-different-from-slug
    slug_field = 'codigo'

    # https://stackoverflow.com/questions/14936160/django-detailview-how-to-display-two-models-at-same-time#14936328
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comentarios'] = models.Estandar.objects.get(
                id=context['object'].id).comentarios_set.all()
        return context


# here i'm gonna add a funtionview for plano
# it will list all ot's and link to the last
# plano that was created (highest planoid)
# (so 2 url families here, /plano and /plano/<ot>)
# for the current user
# in /plano/<ot> i'll add a 'generate plano' button
# (in case there are updates or things needed to be corrected)
@login_required
def plano_lista(request):
    ots = models.Plano.objects.filter(
            autor=request.user.id).values('ot').distinct()

    # no estoy seguro de que esto funcione... ver de cerca primero
    print('request.user =', request.user)
    print('request.user.id =', request.user.id)
    return render(request,
                  template_name="registro/listaplanos.html",
                  context={'ots': ots})


@login_required
def plano_detalle(request, ot):
    plano = models.Plano.objects.filter(ot=ot, autor=request.user.id).last()
    # show the last one created with such ot
    plano_detalle = models.DetallePlano.objects.filter(planoid=plano.planoid)

    generarplanos.generate_and_save_plano(plano.planoid,
                                          plano_detalle,
                                          settings.MEDIA_URL+"estandar",
                                          settings.MEDIA_ROOT+"/estandar",
                                          settings.MEDIA_ROOT+"/planos")

    # check if there are any comments...
    there_are_comments = 0 < sum(
            map(lambda x: len(x.comentario), plano_detalle))

    return render(request,
                  template_name="registro/detalleplano.html",
                  context={'ot': ot,
                           'plano': plano,
                           'plano_detalle': plano_detalle,
                           'there_are_comments': there_are_comments})


def inicio(request):
    return render(request,
                  template_name='registro/base.html')


def instrucciones(request):
    return render(request,
                  template_name='registro/instrucciones.html',
                  context={'MEDIA_URL': settings.MEDIA_URL})


def catalogo(request):
    return redirect(settings.STATIC_URL+'other/catalogo.pdf')

registro/templates/registro/base.html
{% load static %}

<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
		{% block css %}
			<link rel="stylesheet" href="{% static 'css/style.css' %}">
		{% endblock %}
		<title>{% block title %}Estandar{% endblock %}</title>
	</head>

	<body>
		{% block navbar %}
			{% include './navbar.html' %}
		{% endblock %}
		<br>
		<main>
		{% block content %}{% endblock %}
		</main>
	</body>
</html>

registro/templates/registro/buscador.html
{% extends "registro/base.html" %}

{% block content %}
<form action='' method="get">
	<!--{% csrf_token %}-->

	{# aca quiero poner: un dropbox o textbox con autocomplete... y que se pueda filtrar por categoria! #}
	<input type="text" id='codigo'>
	<br>
	<input type="submit" value="Buscar">
</form>
{% endblock %}

registro/templates/registro/codigos-alt.html
<head>
	<style>
		.tinyimage {
			width:100px;
		}
	</style>
</head>

<body>
<table>
{% for e in estandar %}
		<tr>
			<td><img class="tinyimage" src="/media/{{e.imagen}}"></img></td>
			<td>
				<a href="codigos/{{e.id}}">
				{{e.codigo}}
				</a>
			</td>
		</tr>
	</a>
{% endfor %}
</table>
</body>

registro/templates/registro/detalleplano.html
{% extends "./base.html" %}

{% block content %}

<h2>OT {{ot}}</h2>

<div class="plano">
{# primero la imagen, si es que existe #}
<img id="plano" src="/imagenes/planos/{{ plano.planoid }}.png">
<!-- after deployment this wont work (not even when debug mode is off, accoding to the documentation) -->
</div>

{# datos del plano (cuando fue creado, que cliente, cuando fue generada #}
{# datos del detalle de plano (cada pieza, por orden, con sus detalles) #}

<!--
<br>
<br>
<br>
<p id="info-plano">creado el {{plano.fecha}}</p>
-->

<br>
<div id="tabla-plano-detalle">
	<table id="planodetalle">
		<tr>
			<th>Cantidad</th>
			<th>Codigo Estandar</th>
			<th>Tipo</th>
			<th>Ancho [mm]</th>
			<th>Alto [mm]</th>
			{% if there_are_comments %}
				<th>Comentarios</th>
			{% endif %}
		</tr>
	{% for pd in plano_detalle %}
		<tr>
			<td>{{pd.cantidad}}</td>
			<td>{{pd.codigo}}</td>
			<td style="width:100%">{{pd.tipo}}</td>
			<td>{{pd.ancho_mm}}</td>
			<td>{{pd.alto_mm}}</td>
			{% if there_are_comments %}
				<td>{{pd.comentario}}</td>
			{% endif %}
		</tr>
	{% endfor %}
	</table>
</div>

<br>
<form action=''>
	<input type='submit' value="Regenerar plano">
</form>


{% endblock %}

registro/templates/registro/estandar_detail.html
{% extends "./base.html" %}

{% block content %}
<h2>{{object.codigo}}</h2>
<b>Categoria:</b> {{object.categoria}}

<br><br>

<!-- ok for now this works... but after deployment it wont (not even when debug mode is off, accoding to the documentation-->
<img width="300 px" src="/imagenes/{{ object.imagen }}">

<br><br>
{# mostramos los comentarios si existen; si no, mostramos link para agregar comentarios #}
<!--
{% if comentarios %}
	<ul>
	{% for c in comentarios %}
	<li>{{c.comentario}}</li>
	{% endfor %}
	</ul>
{% else %}
	<a href="{% url 'registro:nuevo-codigo-comentarios' %}?codigo={{object.codigo}}">Agregar comentarios</a>
{% endif %}
-->
{% endblock %}

registro/templates/registro/estandar_list.html
{% extends "registro/base.html" %}

{% block content %}
<ul>
{% for codigo in object_list %}
	<li><a href="{% url 'registro:codigos-listview' %}/{{codigo.codigo}}">{{codigo.codigo}}</a></li>
{% empty %}
	<li>Sin codigos registrados.</li>
{% endfor %}
</ul>
{% endblock %}

registro/templates/registro/instrucciones.html
{% extends 'registro/base.html' %}

{% block content %}

<h3>Planos Estandar</h3>

<div id="texto-instrucciones">
<p>Esta app web sirve para generar planos compuestos por planos <a target="_blank" href={% url 'registro:catalogo' %}>estandar</a>.

<p>Para hacer uso de un plano estandar, este debe haber sido previamente cargado.</p>

<h4>¿Cómo cargar un código estandar?</h4>
<p>Si un código estandar todavía no fue cargado, podés agregarlo ingresando al menú [≡ Estandar],<br>seleccionando <a href="{% url 'registro:nuevo-codigo' %}">Cargar Nuevo Estandar</a> e introduciendo los datos del catálogo.</p>

<ol><li>Se ingresa el código estandar y se escoge la categoría.</li><li> Para la imagen, <ol><li>seleccionamos la del catálogo (seleccionamos la imagen solamente, sin el nombre ni los comentarios),</li><li> copiamos  con ctrl+c o usando el menu,</li><li>luego pegamos (con ctrl+v).</li></ol> <li>Por último, click en 'Guardar'</li></ol>
<p>y ya tenemos el nuevo plano estandar agregado.</p>

<!--<p>(Se pueden agregar tambien los comentarios que figuran en el catálogo, una vez cargado.)</p>-->

<p>Los planos estandar que ya fueron cargados, se pueden acceder mediante el menu, siguiendo el enlace <a href="{% url 'registro:codigosporcategoria' %}">Planos Estandar</a> </p>

<h4>Generar un nuevo plano (compuesto por planos estandar)</h4>
<p>Para crear tus propios planos, elegí <a href="{% url 'registro:nuevo-plano' %}">Generar Nuevo Plano</a> en el menú, donde ingresás el OT o Nro. de Venta, seguido de los detalles del mismo.</p>

<p>Tras guardar, el plano se genera automáticamente.</p>

<h4>Detalles para la carga</h4>
<p>Para ver la lista de planos que ya generaste, utilizá la opción <a href="{% url 'registro:listaplanos' %}">Ver Mis Planos</a> del menú.</p>


{% endblock %}

registro/templates/registro/listacodigos.html
{% extends 'registro/base.html' %}

{% block content %}

<form action='' method="post">
	{% csrf_token %}
	{{ selectfilter.as_p }}
</form>

{#<br>{{selectfilter.GET.filtro}}<br>#}

{# it works! of course this can be improved #}
{% for categoria,codigo in codigos.items %}
	{% if codigo %}
	<h2>{{categoria}}</h2>
	<ul>
		{% for c in codigo %}
		<li><a href="{% url 'registro:codigos-detailview' c %}">{{c}}</a>
			{% if showimages %}
			<br><img src="{{MEDIA_URL}}{{c.imagen}}"/><br>
			{% endif %}
		</li>
		{% endfor %}
	</ul>
	{% endif %}
{% endfor %}

{% endblock %}

registro/templates/registro/listacodigos2.html
{% extends 'registro/base.html' %}

{% block content %}

<form action='' method="post">
	{% csrf_token %}
	{{ selectfilter.as_p }}
</form>

{% block css %}
<style>
	#content ul {
		list-style:none;
	}

	#content ul li {
		float:left;
		padding:10px;
		/*border-bottom:1px solid #000;
		border-right:1px solid #000;*/ }

	/*
	#content ul li:nth-child(3n) {
		background-color:#888;
	}
	*/

	#content ul li:nth-child(3n+1) {
		clear:both;
		/*border-left:1px solid #000;*/
		/*background-color:#ccc;*/
	}

	#content ul li:nth-child(-n+3) {
		/*border-top:1px solid #000;*/
	}
</style>
{% endblock %}

{# it works! of course this can be improved #}
{% for categoria,codigo in codigos.items %}
	{% if codigo %}
	<h2>{{categoria}}</h2>
	<ul>
		{% for c in codigo %}
		<li><a href="{% url 'registro:codigos-detailview' c %}">{{c}}</a>
			{% if showimages %}
				<img src="/media/{{c.imagen}}"/>
			{% endif %}
		</li>
		{% endfor %}
	</ul>
	<br>
	{% endif %}
{% endfor %}

{% endblock %}

registro/templates/registro/listaplanos.html
{% extends 'registro/base.html' %}

{% block content %}

{# lists distinct ots (ot=orden de trabajo, the id in the glass provider internal system) #}
{% for p in ots %}
	<ul>
	{% if p %}
		<li>
			<a href="planos/{{p.ot}}">{{p.ot}}</a>
		</li>
	{% else %}
		<p>(nada)</p>
	{% endif %}
	</ul>
{% endfor %}

{% endblock %}

registro/templates/registro/navbar.html
{% load static %}
<script defer type="text/javascript" src="{% static 'js/toggle.js' %}"></script>

<nav>
	<div class="dropdown">
		<button onclick="toggleLeftDropdown()" class="dropbtn">≡ Estandar</button>
		<!--<a href="#home" class="active">Estandar</a>-->
		<div class="dropdown-content" id="leftDropdown">
			{% if user.is_authenticated %}
				<a href="{% url 'registro:nuevo-plano' %}">Generar Nuevo Plano</a>
				<a href="{% url 'registro:nuevo-codigo' %}">Cargar Nuevo Estandar</a>
				<hr>
				<a href="{% url 'registro:listaplanos' %}">Ver Mis Planos</a>
				<a href="{% url 'registro:codigosporcategoria' %}">Ver Códigos Estandar Cargados</a>
				<a target="_blank" href="{% url 'registro:catalogo' %}">Ver Catálogo (externo)</a>
				<hr>
				<a href="{% url 'registro:instrucciones' %}">¿Cómo usar?</a>
			{% else %}
				<a href="{% url 'login' %}">Iniciar Sesión</a>
			{% endif %}
			<hr><hr>
			<a href="/">Menú princial</a>
		</div>
	</div>
		
	{% if user.is_authenticated %}
		<div class="dropdown right">
			<button onclick="toggleRightDropdown()" class="dropbtn">{{request.user}}<!--🙂--></button>
			<div class="dropdown-content" id="rightDropdown">
				<a href="{% url 'password_change' %}">Cambiar contraseña</a>
				<a href="{% url 'logout' %}">Cerrar Sesión</a>
			</div>
		</div>
	{% endif %}
</nav>

registro/templates/registro/nuevo-codigo-comentarios.html
{% extends './base.html' %}
{% load static %}

{% block content %}
<h3>Comentarios</h3>
<script type="text/javascript" src="{% static 'js/jquery-3.6.0.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.formset.js' %}"></script>
<script type="text/javascript">
	$(function() {
			$('#myform tbody tr').formset();
	})
</script>

	<!--<form id="myform" action='/comentariosformset' method="post" enctype="multipart/form-data">-->
	<!--<form id="myform" action='' method="post" enctype="multipart/form-data">-->
	<form id="myform" method="post" enctype="multipart/form-data">
	{% csrf_token %}
	codigo: {{codigo}}<br><br>
	<table>
		{{ formset.as_table }}
	</table>
	<br>
	<input type="submit" value="Guardar">
</form>
{% endblock %}

registro/templates/registro/nuevo-codigo.html
{% extends "./base.html" %}
{% load static %}

{% block content %}

<form action='' method="post" enctype="multipart/form-data">
	{% csrf_token %}
		{{ form.as_p }}
	<br>


	<!--
	<button type="button" id="pastebutton">p</button>
	<br>
	<br>
	esto no funciona! -->

	<input type="submit" value="Guardar">
</form>

<script defer type="text/javascript" src="{% static 'js/imagepasting.js' %}"></script>

{% endblock %}

registro/templates/registro/nuevoplano.html
{% extends "./base.html" %}
{% load static %}

{% block content %}

<script type="text/javascript" src="{% static 'js/jquery-3.6.0.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.formset.js' %}"></script>
<script type="text/javascript">
	$(function() {
			$('#myform tbody').formset();
	})
</script>

<form id="myform" method="post" enctype="multipart/form-data">
	{% csrf_token %}
	{{ ot_form.as_p }}

	{% if error_message %}
    <div class="error-alert">
        {{ error_message }}
    </div>
	{% endif %}

	{{ plano_formset.management_form }}
		{% for plano_form in plano_formset %}
		<table>
				{{ plano_form.as_table }}
				<!--<tr class="delete-btn-container"></tr>-->
		</table>
		{% endfor %}

	<div class="add-btn-container"></div>

	<br>
	<input type="submit" value="Guardar">
</form>

{% endblock %}